### ISSUE TITLE
how to solve this problem that is the system prompts "benchmark:command not found“when i run this program?

### ISSUE THREAD

**Issue by LNanyi** [eXascaleInfolab/LFR-Benchmark_UndirWeightOvp#2]

**Comment by luav** [comment]
Hi  @LNanyi , I updated the [Compilation](https://github.com/eXascaleInfolab/LFR-Benchmark_UndirWeightOvp#compilation) section of the readme:
> In order to compile, type: `$ make`.  
> This command builds the binary named `TAG=lfrbench_udwo` as specified in the `./makefile`. In the following description, the application (`lfrbench_udwo`) is referred to as `benchmark` for convenience.

Thus, you should execute `./lfrbench_udwo` (instead of `./benchmark`) upon the successful compilation.
