### ISSUE TITLE
Weight Mixing Parameter Clarification

### ISSUE THREAD

**Issue by aliyassin4** [eXascaleInfolab/LFR-Benchmark_UndirWeightOvp#5]
Hello,

Based on my comprehension, it appears that the weight distribution adheres to a power law distribution, and you can adjust it by manipulating the weight exponent and the weight mixing parameter. I'm curious to know which specific type of power law distribution you are employing. Are you using any of the following:
1. Lognormal
2. Exponential
3. Truncated power law
4. Stretched exponential
5. Lognormal (positive)

Best,
Ali

**Comment by luav** [comment]
Hi @aliyassin4 ,
this fork of the LFR-Benchmark extends (see the [changelog](https://github.com/eXascaleInfolab/LFR-Benchmark_UndirWeightOvp#changelog)) the original version without affecting the original parameterized weight generation.

See the author's paper and the source code for details about the weight generation:
A. Lancichinetti, S. Fortunato, and F. Radicchi.(2008) [Benchmark graphs for testing community detection algorithms.](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.78.046110) Physical Review E, 78
